// Builds search-index.js — the full text of every explainer, so the homepage
// search box can match article bodies instead of just titles and summaries.
//
//   node search-index.mjs
//
// Output is a plain <script> (not JSON) so it loads over file:// as well as
// https://, matching how share-posts.js already works in this project.
import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { gzipSync } from 'node:zlib';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, 'search-index.js');

// Page furniture that appears on every explainer — indexing it would make
// every query match every post.
const CHROME = [
  /Read at your level/gi,
  /Summary\s*Manager\s*Technical/gi,
  /AI Blog Explainers/gi,
  /Back to all explainers/gi,
  /Prev(ious)?\s*·?\s*Next/gi,
  /Copy link/gi,
  /Share on (X|LinkedIn)/gi,
  /Download image/gi,
  /Original article/gi,
  /Figure \d+/gi,
  /Explainer artifact generated from[^.]*\./gi,
];

// The article proper runs from the hero to the floating share widget; outside
// that sit <head> metadata, the top bar and the share buttons. The hero itself
// (kicker, headline, lede, meta strip) is split off from the article body,
// because it is what the result card already shows — worth matching against,
// not worth quoting back as a snippet.
function split(html) {
  let a = html.indexOf('<header class="hero"');
  if (a === -1) a = Math.max(html.indexOf('<body'), 0);
  let z = html.indexOf('<div id="aibe-share"');
  if (z === -1) z = html.length;
  const article = html.slice(a, z);
  const h = article.indexOf('</header>');
  return h === -1 ? ['', article] : [article.slice(0, h), article.slice(h + 9)];
}

function extract(html) {
  let t = html;
  t = t.replace(/<!--[\s\S]*?-->/g, ' ');
  t = t.replace(/<(script|style|svg|noscript)\b[\s\S]*?<\/\1>/gi, ' ');
  t = t.replace(/<[^>]+>/g, ' ');
  // decode the entities that actually occur in these pages
  const ents = {
    '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'",
    '&nbsp;': ' ', '&mdash;': '—', '&ndash;': '–', '&rsquo;': '’', '&lsquo;': '‘',
    '&ldquo;': '“', '&rdquo;': '”', '&hellip;': '…', '&times;': '×',
    '&middot;': '·', '&rarr;': '→', '&larr;': '←', '&check;': '✓',
  };
  t = t.replace(/&[a-z#0-9]+;/gi, (m) => ents[m.toLowerCase()] ?? ' ');
  for (const re of CHROME) t = t.replace(re, ' ');
  return t.replace(/\s+/g, ' ').trim();
}

function build() {
  const dir = resolve(here, 'explainers');
  const docs = {};
  for (const f of readdirSync(dir).filter((f) => f.endsWith('.html')).sort()) {
    // [hero, body] — the homepage matches both and snippets from the second.
    const parts = split(readFileSync(join(dir, f), 'utf8')).map(extract);
    if (parts[1].length < 200) {
      console.warn(`  ! ${f} extracted only ${parts[1].length} chars of body — check the template`);
    }
    docs[f.replace(/\.html$/, '')] = parts;
  }
  if (!Object.keys(docs).length) throw new Error('no explainers found');

  const body =
    `// Generated by search-index.mjs — do not edit. Rebuild: node search-index.mjs\n` +
    `window.__SEARCH__=${JSON.stringify(docs)};\n`;
  writeFileSync(OUT, body);

  const raw = statSync(OUT).size;
  const gz = gzipSync(body).length;
  return { count: Object.keys(docs).length, raw, gz };
}

const s = build();
console.log(`indexed ${s.count} explainers`);
console.log(`search-index.js  ${(s.raw / 1024).toFixed(0)} KB raw · ${(s.gz / 1024).toFixed(0)} KB gzipped (what visitors download)`);
