// Reads the real numbers off the site and writes video/stats.js, which
// launch.html loads. render.mjs runs this automatically, so a re-render always
// reflects the site as it stands rather than whatever was hard-coded months ago.
//
//   node video/stats.mjs        # print + write video/stats.js
//
// The explainer count is floored to a round number and shown as "N+". The
// archive only ever grows, so that claim cannot go stale between renders —
// which a bare count does, every single day the pipeline runs.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const SITE = resolve(here, '..');

export function readStats() {
  const html = readFileSync(resolve(SITE, 'index.html'), 'utf8');
  const start = html.indexOf('const POSTS = [');
  if (start === -1) throw new Error('POSTS array not found in index.html');
  const end = html.indexOf('\n];', start);
  const block = html.slice(start, end);

  const posts = (block.match(/\{slug:/g) || []).length;
  const sources = new Set([...block.matchAll(/source:"([^"]+)"/g)].map((m) => m[1]));
  if (!posts) throw new Error('parsed 0 posts — has the POSTS format changed?');

  // Round down to a tens boundary, but never claim more than there are.
  const bucket = posts >= 20 ? Math.floor(posts / 10) * 10 : Math.floor(posts / 5) * 5;

  return { posts, bucket, sources: sources.size, sourceNames: [...sources].sort() };
}

export function writeStats() {
  const s = readStats();
  const out = resolve(here, 'stats.js');
  writeFileSync(
    out,
    `// Generated by video/stats.mjs — do not edit. Regenerate with: node video/stats.mjs\n` +
      `window.__STATS__ = ${JSON.stringify({ posts: s.posts, bucket: s.bucket, sources: s.sources })};\n`
  );
  return s;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const s = writeStats();
  console.log(`posts   ${s.posts}  ->  displayed as "${s.bucket}+"`);
  console.log(`sources ${s.sources}  (${s.sourceNames.join(', ')})`);
  console.log('wrote video/stats.js');
}
